--- #YAML:1.0
name:                Net-VNC
version:             0.36
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Crypt::DES:                    0
    Image::Imlib2:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
